#
# Copyright 2020 Prathab Murugan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

###############################################################################
# Server properties
###############################################################################
server:
  port: 8080
  cors.allowedOrigins: http://localhost:3000


###############################################################################
# Spring
###############################################################################
spring:
  mail:
    host: ${springMailHost:"none"}
    username: ${springMailUsername:"none"}
    password: ${springMailPassword:"none"}
    port: 465
    protocol: 'smtps'
    devMode: true
    debug: true
    test-connection: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
        format_sql: true
  application:
    name: "myhome-service"
  devtools:
    restart:
      enabled: true
  h2.console:
    enabled: true
    settings.web-allow-others: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    mail:
      enabled: false

###############################################################################
# Custom properties
###############################################################################
api:
  public:
    login.url.path: "/auth/login"
    registration.url.path: "/users"
    h2console.url.path: "/h2-console/**"
    actuator.url.path: "/actuator/**"
    forgot-password.url.path: "/users/password"
    resend-confirmation-email.url.path: "/users/*/email-confirm-resend"
    confirm-email.url.path: "/users/*/email-confirm/**"
    cors.url.path: "/**"

email:
  template:
    path: "templates/mail"
    format: ".html"
    encoding: "UTF-8"
    mode: "HTML"
    cache: false
  location:
    #      matches with 'locales/mails', 'locales/mails_en' 'locales/mails_en_US' e.t.c
    path: "locales/mails"
    encoding: "UTF-8"
    cacheSeconds: 0

authorization:
  token:
    header:
      name: "Authorization"
      prefix: "Bearer"

tokens:
  email:
    expiration: 1d
  reset:
    expiration: 1d

files:
  maxSizeKBytes: 480
  compressionBorderSizeKBytes: 240
  #   float value from 0 to 1
  compressedImageQuality: 0.5

token:
  expiration_time: 10d
  secret: "sgahjsdhfjahsdfhjkahjsdfyquiwuhekrjkhsjkdfakjhskdfhiauwehriqwekrhkhknfdkkanskdfkakshdfhuqiwheuriqjwkefkahksdhfkaskdhfkhuiquhweurihqjwkerjqhkwhekfhkanksdnkfakhsdkfhiiqiwherqjowjeorjoqweoriewoq"